import type { Profile, LiveStream, StreamCategory, Gift, CoinPackage, Report, NotificationItem, WalletTransaction } from '../types';

export const MOCK_CATEGORIES: StreamCategory[] = [
  { id: 'cat-1', name: 'Just Chatting', slug: 'just-chatting', iconName: 'MessageSquare', sortOrder: 1 },
  { id: 'cat-2', name: 'Music & DJ', slug: 'music', iconName: 'Music', sortOrder: 2 },
  { id: 'cat-3', name: 'Gaming', slug: 'gaming', iconName: 'Gamepad2', sortOrder: 3 },
  { id: 'cat-4', name: 'Dance & Vibes', slug: 'dance', iconName: 'Flame', sortOrder: 4 },
  { id: 'cat-5', name: 'Lifestyle & Travel', slug: 'lifestyle', iconName: 'Compass', sortOrder: 5 },
  { id: 'cat-6', name: 'Creative & Art', slug: 'art', iconName: 'Palette', sortOrder: 6 },
  { id: 'cat-7', name: 'Fitness & Sports', slug: 'fitness', iconName: 'Dumbbell', sortOrder: 7 },
  { id: 'cat-8', name: 'Cooking & Food', slug: 'cooking', iconName: 'Utensils', sortOrder: 8 },
];

export const MOCK_CREATORS: Profile[] = [
  {
    userId: 'user-c1',
    displayName: 'Aria Vibe',
    username: '@aria_vibe',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400',
    coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200',
    bio: '🎵 Live Acoustic Singer & Late Night Conversations | VIP Creator',
    country: 'United States',
    language: 'English',
    followersCount: 142500,
    followingCount: 230,
    totalLikes: 890000,
    isLive: true,
  },
  {
    userId: 'user-c2',
    displayName: 'DJ Neon Pulse',
    username: '@neonpulse_dj',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200',
    bio: '🎧 EDM Electronic Producer & Live DJ Sets | Drops every night 10 PM EST',
    country: 'United Kingdom',
    language: 'English',
    followersCount: 98400,
    followingCount: 120,
    totalLikes: 640000,
    isLive: true,
  },
  {
    userId: 'user-c3',
    displayName: 'Kira Star',
    username: '@kirastar_jp',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400',
    coverUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200',
    bio: '✨ Anime & Gaming Cosplayer | Valorant Pro | Daily PK Battle Queen',
    country: 'Japan',
    language: 'Japanese / English',
    followersCount: 210000,
    followingCount: 85,
    totalLikes: 1450000,
    isLive: true,
  },
  {
    userId: 'user-c4',
    displayName: 'Chef Matteo',
    username: '@matteocooking',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    coverUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200',
    bio: '🍝 Italian Masterchef | Live Pasta & Pizza Crafting',
    country: 'Italy',
    language: 'Italian / English',
    followersCount: 54300,
    followingCount: 310,
    totalLikes: 290000,
    isLive: false,
  },
  {
    userId: 'user-c5',
    displayName: 'Zoe Dance Flow',
    username: '@zoedance',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200',
    bio: '💃 Hip Hop & K-Pop Dance Covers | Let us party together!',
    country: 'South Korea',
    language: 'Korean / English',
    followersCount: 178000,
    followingCount: 190,
    totalLikes: 1120000,
    isLive: true,
  }
];

export const MOCK_STREAMS: LiveStream[] = [
  {
    id: 'stream-101',
    creatorId: 'user-c1',
    creator: MOCK_CREATORS[0],
    title: '🎤 Late Night Unplugged Session + Acoustic Request Songs!',
    description: 'Come chill, chat, and request your favorite indie and pop songs live!',
    categoryId: 'cat-2',
    categoryName: 'Music & DJ',
    coverUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    status: 'live',
    viewerCount: 4890,
    peakViewers: 6200,
    totalLikes: 34200,
    totalGiftsCoins: 125000,
    startedAt: '45 mins ago',
    tags: ['Music', 'LiveSinging', 'Chill'],
    isPK: false,
  },
  {
    id: 'stream-102',
    creatorId: 'user-c3',
    creator: MOCK_CREATORS[2],
    title: '🔥 INTENSE PK BATTLE VS NEON PULSE! HELP ME WIN 👑',
    description: 'We have 5 minutes to beat the record! Send your rockets and crowns!',
    categoryId: 'cat-3',
    categoryName: 'Gaming',
    coverUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    status: 'live',
    viewerCount: 12400,
    peakViewers: 15800,
    totalLikes: 98000,
    totalGiftsCoins: 480000,
    startedAt: '12 mins ago',
    tags: ['PKBattle', 'Gaming', 'Cosplay'],
    isPK: true,
    pkOpponentId: 'user-c2',
  },
  {
    id: 'stream-103',
    creatorId: 'user-c2',
    creator: MOCK_CREATORS[1],
    title: '🎧 VIP Ibiza House & EDM DJ Set Live from London Studio',
    description: 'High energy bass drops and exclusive remixes. Put your headphones on!',
    categoryId: 'cat-2',
    categoryName: 'Music & DJ',
    coverUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    status: 'live',
    viewerCount: 8900,
    peakViewers: 10400,
    totalLikes: 76000,
    totalGiftsCoins: 310000,
    startedAt: '1 hour ago',
    tags: ['DJSet', 'EDM', 'Ibiza'],
    isPK: true,
    pkOpponentId: 'user-c3',
  },
  {
    id: 'stream-104',
    creatorId: 'user-c5',
    creator: MOCK_CREATORS[4],
    title: '✨ K-Pop Dance Workshop & Choreography Challenge!',
    description: 'Learning the newest BTS & NewJeans dance moves step-by-step.',
    categoryId: 'cat-4',
    categoryName: 'Dance & Vibes',
    coverUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    status: 'live',
    viewerCount: 3200,
    peakViewers: 4100,
    totalLikes: 21500,
    totalGiftsCoins: 65000,
    startedAt: '25 mins ago',
    tags: ['Dance', 'KPop', 'Fitness'],
  }
];

export const MOCK_GIFTS: Gift[] = [
  { id: 'g-1', name: 'Heart', description: 'Show some love', coinPrice: 10, imageUrl: '💖', active: true, sortOrder: 1, category: 'Popular' },
  { id: 'g-2', name: 'Rose', description: 'A sweet rose', coinPrice: 20, imageUrl: '🌹', active: true, sortOrder: 2, category: 'Popular' },
  { id: 'g-3', name: 'Star', description: 'Shine bright', coinPrice: 50, imageUrl: '⭐', active: true, sortOrder: 3, category: 'Popular' },
  { id: 'g-4', name: 'Fire', description: 'Pure hype!', coinPrice: 100, imageUrl: '🔥', active: true, sortOrder: 4, category: 'Vibe' },
  { id: 'g-5', name: 'Crown', description: 'Royal recognition', coinPrice: 500, imageUrl: '👑', active: true, sortOrder: 5, category: 'Luxury' },
  { id: 'g-6', name: 'Diamond', description: 'Unstoppable sparkling gift', coinPrice: 1000, imageUrl: '💎', active: true, sortOrder: 6, category: 'Luxury' },
  { id: 'g-7', name: 'Rocket', description: 'Blast off to the top ranking', coinPrice: 2500, imageUrl: '🚀', active: true, sortOrder: 7, category: 'Special' },
  { id: 'g-8', name: 'Trophy', description: 'Ultimate Champion Trophy', coinPrice: 5000, imageUrl: '🏆', active: true, sortOrder: 8, category: 'Special' },
];

export const MOCK_COIN_PACKAGES: CoinPackage[] = [
  { id: 'cp-1', coins: 100, bonusCoins: 0, priceUSD: 0.99 },
  { id: 'cp-2', coins: 500, bonusCoins: 50, priceUSD: 4.99, badge: 'Popular' },
  { id: 'cp-3', coins: 1200, bonusCoins: 200, priceUSD: 9.99, badge: 'Best Value' },
  { id: 'cp-4', coins: 6500, bonusCoins: 1200, priceUSD: 49.99, badge: '+20% Extra' },
  { id: 'cp-5', coins: 14000, bonusCoins: 3500, priceUSD: 99.99, badge: 'VIP Pack' },
];

export const MOCK_TRANSACTIONS: WalletTransaction[] = [
  { id: 'tx-101', userId: 'me', type: 'coin_purchase', amount: 1200, currencyType: 'COINS', description: 'Purchased 1,200 Coins Package', status: 'completed', createdAt: '2026-09-24 18:20' },
  { id: 'tx-102', userId: 'me', type: 'gift_sent', amount: -500, currencyType: 'COINS', referenceId: 'g-5', description: 'Sent 👑 Crown to Aria Vibe', status: 'completed', createdAt: '2026-09-24 19:10' },
  { id: 'tx-103', userId: 'me', type: 'gift_sent', amount: -100, currencyType: 'COINS', referenceId: 'g-4', description: 'Sent 🔥 Fire to Kira Star', status: 'completed', createdAt: '2026-09-24 19:40' },
];

export const MOCK_REPORTS: Report[] = [
  { id: 'rep-1', reporterId: 'usr-9', reporterName: 'GamerAlex', targetType: 'chat', targetId: 'msg-99', targetName: '@troll_99', reason: 'Spamming inappropriate language in live chat', status: 'pending', createdAt: '10 mins ago' },
  { id: 'rep-2', reporterId: 'usr-14', reporterName: 'Elena_V', targetType: 'stream', targetId: 'stream-104', targetName: 'Zoe Dance Flow', reason: 'Copyright music flag review requested', status: 'reviewing', createdAt: '1 hour ago' },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  { id: 'n-1', type: 'live', title: 'Aria Vibe is LIVE!', message: 'Aria Vibe just started streaming: Late Night Unplugged Session', read: false, createdAt: '45 mins ago', linkUrl: 'stream-101' },
  { id: 'n-2', type: 'gift', title: 'Gift Received!', message: 'User @cool_fan sent you 1x 👑 Crown (500 Coins)', read: false, createdAt: '2 hours ago' },
  { id: 'n-3', type: 'pk', title: 'PK Battle Victory!', message: 'Congratulations! You won the PK Battle against DJ Neon Pulse', read: true, createdAt: '1 day ago' },
];
